### ISSUE TITLE
About performance  of WFLW subsets 

### ISSUE THREAD

**Issue by starhiking** [ZhenglinZhou/STAR#10]
Wonderful work!

We wanna cite and compare your great work, but lack some results in WFLW subsets.

Can you give the performance (NME, FR and AUC ) of WFLW subset ?

**Comment by ZhenglinZhou** [comment]
Hi @starhiking, thanks for your interest!

The full results can be found in appendix (Table 12, page 13) of  [arxiv version](https://arxiv.org/pdf/2306.02763.pdf). If you have any question, please let me know.

**Comment by starhiking** [comment]
Thanks!
