### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [ZhenglinZhou/STAR#14]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

- Converted ONNX / TFLite
  https://github.com/PINTO0309/PINTO_model_zoo/tree/main/414_STAR

Thank you.

**Comment by ZhenglinZhou** [comment]
Hi @PINTO0309, thanks for your interest!

Our code is under Apache-2.0 license. If you have any questions, please let me know.

**Comment by PINTO0309** [comment]
Thank you!
