### ISSUE TITLE
Could STAR loss works in coor regression methods?

### ISSUE THREAD

**Issue by DUTyimmy** [ZhenglinZhou/STAR#17]

**Comment by ZhenglinZhou** [comment]
Hi @DUTyimmy, thanks for your interest!

The STAR loss is potentially effective in coordinate regression methods.

The key to implying STAR loss is the estimation of the covariance matrix. To estimate the covariance matrix in coordinate regression methods, one option is to incorporate a covariance prediction branch (consider Cholesky Estimator Net in this [paper](https://arxiv.org/pdf/2004.02980.pdf)). 

If you have any questions, please let me know.
