### ISSUE TITLE
regarding the metadata_path

### ISSUE THREAD

**Issue by anguoyang** [ZhenglinZhou/STAR#18]
Hi @ZhenglinZhou , there is a para named with metadata_path, where can I get it?
```
python evaluate.py --device_ids=0 \
                   --model_path=${model_path} --metadata_path=${metadata_path} \
                   --image_dir=${image_dir} --data_definition={WFLW, 300W, COFW} \ 
```

btw, I downloaded the 300w dataset, it seems the annotation of the test data included in test.ts, just wonder how you split it into full, common and challenge and evaluate them respectively? it seems there is no item in the annotation to tell which image is challenge, thank you

**Comment by ZhenglinZhou** [comment]
Hi @anguoyang!

You can extract the subset of 300W and COFW from the full TSV files by using the image file name provided in the official split files.

If you have any question, feel free to leave a comment.

**Comment by anguoyang** [comment]
@ZhenglinZhou thanks, understand, but the evaluation result on 300w-full is 0.0287 with the evaluate.py, your report is 2.87, which is 100 times, is it correct?
