### ISSUE TITLE
Confidence Score of Detected Facial Landmarks

### ISSUE THREAD

**Issue by Jourtics** [ZhenglinZhou/STAR#19]
Is there any way we can find the confidence score of the detected landmarks?
Like in face Detection, we get confidence score which tells about its accuracy, similarly is it possible in STAR Loss Model.

**Comment by ZhenglinZhou** [comment]
Hi @Jourtics, thanks for your interest!

In STAR, you could consider use the $\sqrt{\lambda_1 \lambda_2}$, $\lambda_1 \/ \lambda_2$ to represent the prediction confidence and ambiguity, respectively.

**Comment by userguazi** [comment]
> 嗨，感谢您的关注！
> 
> 在 STAR 中，您可以考虑使用 λ 1 λ 2 和 λ 1 / λ 2 分别表示预测的置信度和模糊性。

我可以直接从loss函数中找到吗！因为论文里loss函数中有他
