### ISSUE TITLE
Dataset links

### ISSUE THREAD

**Issue by jamesjg** [ZhenglinZhou/STAR#20]
Hi@ZhenglinZhou,

I've been trying to download datasets for this project from the link provided in the README, but the links for COFW and WLFW appear to be broken and I'm unable to access the datasets. Could you please provide updated links for downloading the datasets?

**Comment by ZhenglinZhou** [comment]
Hi @jamesjg, thanks for your kind feedback. The dataset links are listed below:

[COFW](https://data.caltech.edu/records/bc0bf-nc666), [WLFW](https://github.com/wywu/LAB)([Google Drive](https://drive.google.com/open?id=1hzBd48JIdWTJSsATBEB_eFVvPL1bx6UC) | [Baidu Drive](https://pan.baidu.com/s/1paoOpusuyafHY154lqXYrA))

If you have any questions, feel free to leave a comment.

**Comment by jamesjg** [comment]
Thanks!
