### ISSUE TITLE
train on new dataset

### ISSUE THREAD

**Issue by yangli-lab** [ZhenglinZhou/STAR#22]
Thanks for your excellent work. I want to train the STAR model on my own dataset, could give some advice on how to prepare the training data.
Can I finetune the model on my own dataset, with only the face images and corresponding landmarks. I see that in your code, only images and landmarks are the datas used to train the STAR model.
![image](https://github.com/ZhenglinZhou/STAR/assets/72542735/a29dae13-c8f2-4696-b111-c6958a939d54)

**Comment by ZhenglinZhou** [comment]
Hi @yangli-lab, thanks for your interest!

The input params for preprocess function are `img`, `landmarks_target`, `scale`, `center_w`, `center_h` (see [here](https://github.com/ZhenglinZhou/STAR/blob/master/lib/dataset/alignmentDataset.py#L293-L294), `landmarks_5pts` is not used in our exp).

The `scale`, `center_w` and `center_h` are associated with the detected face box and could be calculated as below:

- scale = min(x2 – x1, y2 – y1) / 200 * 1.05
- center_x = (x1 + x2) / 2
- center_y = (y1 + y2) / 2

Therefore, I suggest to first use a face detector to preprocess your own face images, and calculate the needed params. Then you could organize them in a tsv format (like [this](https://drive.google.com/drive/folders/1sg1cZEZoYBxr6hhIdCoykhKhYQt2yKLn)) or rewrite the [AlignmentDataset](https://github.com/ZhenglinZhou/STAR/blob/master/lib/dataset/alignmentDataset.py).

**Comment by yangli-lab** [comment]
sorry for the late reply, thanks for your answer. I've made it.

**Comment by ZhenglinZhou** [comment]
That's great! If you have any further questions, feel free to reopen this issue.
