### ISSUE TITLE
Not properly working in case of occlusion and tilted head pose.

### ISSUE THREAD

**Issue by Jourtics** [ZhenglinZhou/STAR#26]
Hey @ZhenglinZhou 
The STAR model gives extrapolated landmarks in case of occlusion and tilted head pose like this--
![Star_occlusion_3](https://github.com/ZhenglinZhou/STAR/assets/67581281/5fafb27c-4f0e-462a-b145-9fad23db297e)
Is the model not taking care of the above scenarios? Ideally, the landmarks along the lip and facial contour should not be detected. Most of the facial landmark detection models have this issue.

**Comment by ZhenglinZhou** [comment]
Hi @Jourtics, thanks for your interest!

You are right, the model is encouraged to output landmarks with structural constraint, which is seen as robustness in occlusion. To detect the visibility of landmarks, you could consider [LUVLi](https://openaccess.thecvf.com/content_CVPR_2020/papers/Kumar_LUVLi_Face_Alignment_Estimating_Landmarks_Location_Uncertainty_and_Visibility_Likelihood_CVPR_2020_paper.pdf).

Also thanks @TimSC for the kind reply.

If you have other questions, feel free to leave a comment.
