### ISSUE TITLE
Cannot access the parameters

### ISSUE THREAD

**Issue by oguzhanercansyn** [ZhenglinZhou/STAR#4]
The website is broken or cannot accessble from Europe. VPN also does not work. Can you upload them to the google drive or something accessble from Europe?

**Comment by emredog** [comment]
same here, baidu links unavailable it says "No download permission"

**Comment by HaithemH** [comment]
Could you please put it to google drive. Eager to test models

**Comment by ZhenglinZhou** [comment]
Sorry for the late reply. We upload the model to google drive: 
WFLW: https://drive.google.com/file/d/1aOx0wYEZUfBndYy_8IYszLPG_D2fhxrT/view?usp=sharing
COFW: https://drive.google.com/file/d/1Fiu3hjjkQRdKsWE9IgyNPdiJSz9_MzA5/view?usp=sharing
300W: https://drive.google.com/file/d/1NFcZ9jzql_jnn3ulaSzUlyhS05HWB9n_/view?usp=drive_link

We close this issue. If you have any question, please let me know.
