### ISSUE TITLE
label`s format

### ISSUE THREAD

**Issue by Tyler-Chenn** [ZhenglinZhou/STAR#8]
你好，标签的文本结构是什么样子的？

**Comment by ZhenglinZhou** [comment]
Hi @Tyler-Chenn,

对每张图片，标签由`image_path`、`scale`、`center_w`、`center_h`等变量组成。
具体结构可参考[原数据](https://github.com/huangyangyu/ADNet)（COFW数据集较小，下载较为方便），处理可参考Dataset中的[数据处理部分](https://github.com/ZhenglinZhou/STAR/blob/master/lib/dataset/alignmentDataset.py#L263-L274)。
