### ISSUE TITLE
params and flops of the model

### ISSUE THREAD

**Issue by HitBadTrap** [ZhenglinZhou/STAR#9]
你好！我对这篇工作十分感兴趣，想在自己的文章中引用，利用你提供框架，我测得的params=17.18 M，flops=17.52 GMac，请问是否与你测得的相一致呢？

**Comment by HitBadTrap** [comment]
![09575abd34daba5d661dd48bbebd1f9](https://github.com/ZhenglinZhou/STAR/assets/113753579/51137847-7883-42b2-a8f5-e157069a3447)
这是测试的代码

**Comment by HitBadTrap** [comment]
其他的设置使用的是repo里默认的参数

**Comment by ZhenglinZhou** [comment]
您好 @HitBadTrap ，感谢您对我们工作的兴趣！

我们论文中所报的结果是params=13.37 M，该结果可通过以下代码复现：
```python
from thop import profile

print('Results from thop.profile')
input = torch.randn(1, 3, 256, 256).cuda()
flops, params = profile(net, inputs=(input,))
print('FLOPs = ' + str(flops / 1000 ** 3) + 'G')
print('Params = ' + str(params / 1000 ** 2) + 'M')
```

结果如下：
<img width="150" alt="image" src="https://github.com/ZhenglinZhou/STAR/assets/42434623/8013ccaf-7d3a-466e-8e6e-2c64c06a51f7">

更多结果：
| Datasets | Params (MB) | FLOPs (G)|
| --- | --- | --- |
| WFLW | 13.48 | 17.49 |
| 300W | 13.37 | 17.05 |
| COFW | 13.23 | 16.46 |

如果您还有其他问题，欢迎联系我们。
